services:
  react:
    container_name: react
    build: ./docker/react
    tty: true
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
      - 8080:80


